defaults: &defaults
  roles:
    - admin
    - webadmin
    - moderator
    - user
    - volunteer
  default_role: user

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

CONSUMER_KEY: tqfa7iV6zrbglF7Kjr3zg
CONSUMER_SECRET: 4UjibpBNP9EO9gtKkJG952mrE0X6IsaQYHwsT4weYQ
FACEBOOK_KEY: 173872612791834
FACEBOOK_SECRET: 98c61e444430c94e4dba1de6b821eff0